### ISSUE TITLE
Support more decorators

### ISSUE THREAD

**Issue by tam5** [AdamNiederer/ng2-mode#16]
Any reason the current list of decorators is hardcoded to a select few? There are way more decorators that come into everyday use, (`@Injectable`, `@Input`, `@Output`, `@ContentChild`, `@ViewChild`, etc).

Should this be based on a regex?

**Comment by AdamNiederer** [comment]
Most likely - I wrote this back when Angular 2 was still in beta, and those decorators were the only ones I was aware of. We could do something like `@[A-Za-z0-9_]` without much issue.

**Comment by tam5** [comment]
makes sense. care to make the update? or would u like a pr

**Comment by OlleLinderos** [comment]
I make a PR for this. I guess \\(@[A-Za-z0-9_]+\\) could be good enough, although it could be improved.

**Comment by AdamNiederer** [comment]
We now highlight all decorators, as long as the name of the decorator is a valid Typescript identifier. Feel free to re-open or let me know if you're still having trouble after updating `ng2-mode`.
