### ISSUE TITLE
Underscores break syntax highlighting

### ISSUE THREAD

**Issue by nathansizemore** [AdamNiederer/ng2-mode#19]
<img width="559" alt="screen shot 2018-12-27 at 9 35 56 am" src="https://user-images.githubusercontent.com/3423825/50483775-44d73680-09bb-11e9-9d64-172207d31288.png">

**Comment by AdamNiederer** [comment]
Hi! I just rewrote the syntax highlighting, and I believe I fixed this issue. Feel free to re-open and let me know if you're still experiencing any problems with it.

![2019-05-23-231514_564x30_scrot](https://user-images.githubusercontent.com/4571394/58300482-aeb00c80-7db0-11e9-98a9-d6434ba594aa.png)
