### ISSUE TITLE
Keywords as method names sometimes break syntax highlighting

### ISSUE THREAD

**Issue by nathansizemore** [AdamNiederer/ng2-mode#20]
<img width="247" alt="screen shot 2018-12-27 at 9 41 54 am" src="https://user-images.githubusercontent.com/3423825/50483893-bfa05180-09bb-11e9-8d63-fcb96d14931b.png">
<img width="222" alt="screen shot 2018-12-27 at 9 42 17 am" src="https://user-images.githubusercontent.com/3423825/50483894-bfa05180-09bb-11e9-897c-8ae58a599abf.png">

**Comment by AdamNiederer** [comment]
Hi! I just rewrote the syntax highlighting, and I believe I fixed this issue. Feel free to re-open and let me know if you're still experiencing any problems with it.

![2019-05-23-202118_285x215_scrot](https://user-images.githubusercontent.com/4571394/58294498-6a187700-7d98-11e9-8caa-603737b679bd.png)

**Comment by nathansizemore** [comment]
You rule. Thanks!
