### ISSUE TITLE
Angle bracket (>) seems to cause 100% cpu. 

### ISSUE THREAD

**Issue by jmb1026** [AdamNiederer/ng2-mode#21]
### Problem

While following along with [this](https://angular.io/tutorial/toh-pt6) tutorial ng2-ts mode seems to cause emacs to block and use 100% of the CPU. The code in question is from the "Error handling" section, specifically:

```
private handleError<T> (operation = 'operation', result?: T) {
  return (error: any): Observable<T> => {  // Typing the second > on this line causes the issue.
     // ...
  };
}
```

### Environment

* MacOS 10.14.6
* iTerm2 Build 3.3.7
* Angular CLI: 8.3.20
* Node: 12.13.1
* Angular: 8.2.14
* Emacs 26.3

Emacs configuration

```
 ;; Angular/Typescript
 (use-package typescript-mode
    :ensure t)
 
 (use-package ng2-mode
    :ensure t
    :after typescript-mode)
```

### Steps to reproduce

1. `ng new repro` Accept defaults.
2. `cd repro`
3. Launch emacs and open repro/src/app/app.module.ts
4. In the AppModule class, add the following block

```
getRepro() {
  return (): <T> => {
  }
}
```
5. Typing the second gt bracket (>) will reproduce the issue.

### Misc.

* The issue does not happen with only typescript-mode enabled.
* Once the offending block of code is in the file, emacs will hang when attempting to open the file.
* Emacs does not recover. SIGKILL is the only option.

**Comment by LlinksRechts** [comment]
Any updates on this? What I have found out:
- this seems to only be a problem for generics in return types in lambdas
- it seems to be an issue with syntax highlighting; SIGUSR2 can throw emacs out of the loop, which prints the following stack trace:
  ```
  * #f(compiled-function () #<bytecode 0x166b8e1>)()    
    ng2-ts--inside-lambda-args-p(119)                   
    ng2-ts--highlight-lambda-args-fn(131)               
    font-lock-fontify-keywords-region(1 131 nil)        
    font-lock-default-fontify-region(1 131 nil)         
  ```
- The problem does not occur with brackets around the problematic type, ie. instead of `(): Promise<void> => {}`, use `(): (Promise<void>) => {}` (-> temporary fix)

**Comment by LlinksRechts** [comment]
For anyone else running into this issue: I fixed it using
```diff
--- a/ng2-ts.el
+++ b/ng2-ts.el
@@ -198,6 +198,7 @@
                            (min bound (ng2-ts--end-of-lambda-args (point))) 1))
       (and (ignore-errors
              ;; Skip forward if we wind up in the space between the args and the =>
+             (save-match-data (while (looking-at ">") (forward-char)))
              (ng2-ts--skip-whitespace)
              (forward-char 2)
              (prog1 (save-match-data (search-forward "=>" bound 1))
```

However that is relatively hacky and I really don't know elisp, so I'm not submitting a PR :p

**Comment by AdamNiederer** [comment]
Oh, hey!

Honestly syntax highlighting in emacs is a massive hack anyway. If this fixes it, shoot me an PR and I'll put it in. Rather some edge case not get highlighted than have your editor hang.
