### ISSUE TITLE
set indentation to 2

### ISSUE THREAD

**Issue by CharlesIrvineKC** [AdamNiederer/ng2-mode#3]
It seems the current indentation level is set to 4. How do I set it to 2? Customize seems to show a default of 2, but I get a default of 4. I'm using prelude. Don't know if that makes any difference.

**Comment by CharlesIrvineKC** [comment]
I figured it out after a lot of flailing around. But now I see a new problem. Will open another ticket.

**Comment by skormel** [comment]
I've got the same issue. How did you solve it?

**Comment by AdamNiederer** [comment]
You can customize `typescript-indent-level`, or `sgml-basic-offset` to change your indentation preferences for HTML and Typescript files.
