### ISSUE TITLE
Auto completion in templates

### ISSUE THREAD

**Issue by altschuler** [AdamNiederer/ng2-mode#5]
Cool project! Is there a way to enable auto completion in templates?

**Comment by AdamNiederer** [comment]
If you're looking for syntactic completion, you'll need to write a company backend for Angular 2, which would probably require parsing your component files or connecting to a language server. I don't think that's within the scope of this project.

If you're just looking for heuristic autocompletion, you can enable `company-mode` in your templates and it'll work just like any other mode without a backend.
