### ISSUE TITLE
type-script keymap does not appear to be inherited

### ISSUE THREAD

**Issue by wdmcgrory** [AdamNiederer/ng2-mode#8]
typescript-insert-and-indent does not seem to be called in ng2-ts-mode
I'm not sure this is the right way to correct,
but when I renamed ng2-ts-map to ng2-ts-mode-map, and deleted the (use-local-map ng2-ts-map) from
ng2-ts.el, then I get the "correct" behavior

**Comment by AdamNiederer** [comment]
Yep, that sounds right. Should be resolved in cee5decfea2440e1ecf2c2224c9642a85b2ef086.
